function sweep = rf2MakeTyreBenchSweep(options)
%RF2MAKETYREBENCHSWEEP Create a virtual tyre bench sweep test matrix.
arguments
    options.SlipAngleDeg double = -12:1:12
    options.TargetVerticalLoadN (1,1) double = 5000
    options.CamberDeg (1,1) double = 0
    options.SlipRatio (1,1) double = 0
    options.SpeedMps (1,1) double = NaN
    options.PressureKPa (1,1) double = NaN
    options.CarcassTempC (1,1) double = NaN
    options.DeflectionM (1,1) double = NaN
    options.SettleTimeS (1,1) double = 2
    options.SampleTimeS (1,1) double = 3
    options.OutFile string = ""
end

angles = options.SlipAngleDeg(:);
count = numel(angles);

sweep = table( ...
    (1:count)', ...
    angles, ...
    repmat(options.TargetVerticalLoadN, count, 1), ...
    repmat(options.CamberDeg, count, 1), ...
    repmat(options.SlipRatio, count, 1), ...
    repmat(options.SpeedMps, count, 1), ...
    repmat(options.PressureKPa, count, 1), ...
    repmat(options.CarcassTempC, count, 1), ...
    repmat(options.DeflectionM, count, 1), ...
    repmat(options.SettleTimeS, count, 1), ...
    repmat(options.SampleTimeS, count, 1), ...
    strings(count, 1), ...
    "VariableNames", [ ...
        "step", ...
        "slip_angle_deg", ...
        "target_vertical_load_n", ...
        "camber_deg", ...
        "slip_ratio", ...
        "speed_mps", ...
        "pressure_kpa", ...
        "carcass_temp_c", ...
        "deflection_m", ...
        "settle_time_s", ...
        "sample_time_s", ...
        "notes" ...
    ]);

if strlength(options.OutFile) > 0
    outDir = fileparts(options.OutFile);
    if strlength(outDir) > 0 && ~isfolder(outDir)
        mkdir(outDir);
    end
    writetable(sweep, options.OutFile);
end
end
