#!/usr/bin/env python3
"""Artifact checks for the Tyre Designer ETRTO R.8/R.11 rim overlays."""

from __future__ import annotations

import json
import math
import re
import struct
import hashlib
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
HTML_PATH = REPO_ROOT / "tyres" / "matlab" / "apps" / "tyre_designer" / "assets" / "tyre_designer.html"
BUILDER_PATH = REPO_ROOT / "tyres" / "tools" / "build_tyre_designer_etrto_rim_artifacts.py"
REF_DIR = REPO_ROOT / "tyres" / "analysis" / "_etrto_rim_reference"
OVERLAY_HTML = REPO_ROOT / "tyres" / "analysis" / "etrto_rim_overlay_check.html"
DISPLAY_HTML = REPO_ROOT / "tyres" / "analysis" / "tyre_designer_display_rim_overlay.html"
DISPLAY_PNG = REPO_ROOT / "tyres" / "analysis" / "tyre_designer_display_rim_overlay.png"
SWEEP_JSON = REF_DIR / "etrto_rim_sweep_verification.json"
POINTS_JSON = REF_DIR / "rim_fit_points.json"
BITMAP_ALIGNMENT_JSON = REF_DIR / "etrto_bitmap_alignment_metrics.json"
README = REF_DIR / "README.md"
SOURCE_NOTE = REPO_ROOT / "references" / "etrto_rim_contour_sources.md"
R8_BITMAP_OVERLAY_SVG = REF_DIR / "etrto_R8_bitmap_overlay.svg"
R8_BITMAP_OVERLAY_PNG = REF_DIR / "etrto_R8_bitmap_overlay.png"
R11_BITMAP_OVERLAY_SVG = REF_DIR / "etrto_R11_bitmap_overlay.svg"
R11_BITMAP_OVERLAY_PNG = REF_DIR / "etrto_R11_bitmap_overlay.png"


ZERO_LIMITS = {
    "dhRadiusErrorMm": 1e-6,
    "eErrorMm": 1e-6,
    "r3ErrorMm": 1e-6,
    "r8ErrorMm": 1e-6,
    "humpR8ArcCenterSideViolationMm": 1e-6,
    "humpR8CenterSideErrorMm": 1e-6,
    "humpR8SeatRadiusDirectionErrorDeg": 1e-5,
    "humpR8SeatTangentErrorDeg": 1e-5,
    "humpR3R8TangentErrorDeg": 1e-5,
    "humpR3R8DirectedTangentErrorDeg": 1e-5,
    "humpR3ConnectorDirectedTangentErrorDeg": 1e-5,
    "humpConnectorR8DirectedTangentErrorDeg": 1e-5,
    "humpR8SeatDirectedTangentErrorDeg": 1e-5,
    "hErrorMm": 1e-6,
    "qExcessMm": 1e-6,
    "gErrorMm": 1e-6,
    "bErrorMm": 1e-6,
    "r1ErrorMm": 1e-6,
    "r2ErrorMm": 1e-6,
    "r4ErrorMm": 1e-6,
    "r5ErrorMm": 1e-6,
    "betaErrorDeg": 1e-6,
    "lShortfallMm": 1e-6,
    "beadSeatLineErrorMm": 1e-6,
}


def relative(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT))


def png_size(path: Path) -> tuple[int, int] | None:
    data = path.read_bytes()[:24]
    if len(data) < 24 or data[:8] != b"\x89PNG\r\n\x1a\n" or data[12:16] != b"IHDR":
        return None
    width, height = struct.unpack(">II", data[16:24])
    return width, height


def parse_table(html: str) -> dict[str, str]:
    rows = re.findall(r"<tr><th>(.*?)</th><td>(.*?)</td></tr>", html, flags=re.S)
    return {re.sub(r"<.*?>", "", key).strip(): re.sub(r"<.*?>", "", value).strip() for key, value in rows}


def current_source_hash() -> str:
    return hashlib.sha256(HTML_PATH.read_text(encoding="utf-8").encode("utf-8")).hexdigest()


def assert_numeric_limit(errors: list[str], label: str, raw: str | None, limit: float) -> None:
    if raw is None:
        errors.append(f"missing numeric table row: {label}")
        return
    try:
        value = float(raw)
    except ValueError:
        errors.append(f"non-numeric table row {label}: {raw!r}")
        return
    if abs(value) > limit:
        errors.append(f"{label} exceeds {limit}: {value}")


def check_overlay_html(errors: list[str]) -> None:
    html = DISPLAY_HTML.read_text(encoding="utf-8")
    source_hash = current_source_hash()
    for marker in [
        "Tyre Designer Display Rim Overlay",
        "same ETRTO J/H rim layers used by the Tyre Designer plot",
        "independently reconstructed dimension reference",
        'data-source-html-sha256="',
        source_hash,
        "Generated by",
        "build_tyre_designer_etrto_rim_artifacts.py",
        "Designer H hump",
        "ETRTO R.8/R.11 reference",
        "stroke=\"#f0b85a\"",
        "stroke=\"#72b7ff\"",
    ]:
        if marker not in html:
            errors.append(f"missing display overlay marker: {marker}")

    table = parse_table(html)
    if table.get("passed") != "true":
        errors.append(f"display overlay verification did not pass: {table.get('passed')!r}")
    if table.get("errors") != "[]":
        errors.append(f"display overlay has verification errors: {table.get('errors')!r}")
    for key, limit in ZERO_LIMITS.items():
        assert_numeric_limit(errors, key, table.get(key), limit)
    if float(table.get("humpMaxSampleTurnDeg", "0")) > 35:
        errors.append(f"humpMaxSampleTurnDeg exceeds 35: {table.get('humpMaxSampleTurnDeg')!r}")
    if float(table.get("humpR3ArcSweepDeg", "0")) > 180:
        errors.append(f"humpR3ArcSweepDeg exceeds 180: {table.get('humpR3ArcSweepDeg')!r}")
    if float(table.get("humpR8ArcSweepDeg", "0")) > 135:
        errors.append(f"humpR8ArcSweepDeg exceeds 135: {table.get('humpR8ArcSweepDeg')!r}")
    try:
        hump_count = float(table.get("humpCount", "nan"))
    except ValueError:
        hump_count = float("nan")
    if hump_count != 2:
        errors.append(f"display overlay should show mirrored H humps: humpCount={table.get('humpCount')!r}")


def check_png(errors: list[str]) -> None:
    check_png_file(errors, DISPLAY_PNG, "display overlay PNG", min_width=600, min_height=120)


def check_png_file(errors: list[str], path: Path, label: str, *, min_width: int, min_height: int) -> None:
    size = png_size(path)
    if size is None:
        errors.append(f"{label} is not a PNG: {relative(path)}")
        return
    width, height = size
    if width < min_width or height < min_height:
        errors.append(f"{label} is unexpectedly small: {width}x{height}")
    if path.stat().st_size < 4_000:
        errors.append(f"{label} is unexpectedly small on disk: {path.stat().st_size} bytes")


def check_sweep_json(errors: list[str]) -> None:
    sweep = json.loads(SWEEP_JSON.read_text(encoding="utf-8"))
    source_hash = current_source_hash()
    if sweep.get("sourceHtmlSha256") != source_hash:
        errors.append("sweep JSON was not generated from the current Tyre Designer HTML")
    if sweep.get("generatedBy") != "tyres/tools/build_tyre_designer_etrto_rim_artifacts.py":
        errors.append(f"unexpected sweep generator: {sweep.get('generatedBy')!r}")
    standard = sweep.get("standard") or {}
    if standard.get("caseCount") != 9:
        errors.append(f"expected 9 standard rim cases, got {standard.get('caseCount')!r}")
    if standard.get("failures"):
        errors.append(f"standard rim sweep has failures: {json.dumps(standard.get('failures'), indent=2)}")

    max_errors = standard.get("maxErrors") or {}
    for key, limit in ZERO_LIMITS.items():
        value = float(max_errors.get(key, 0))
        if abs(value) > limit:
            errors.append(f"standard sweep {key} exceeds {limit}: {value}")
    if float(max_errors.get("humpMaxSampleTurnDeg", 0)) > 35:
        errors.append(f"standard sweep humpMaxSampleTurnDeg exceeds 35: {max_errors.get('humpMaxSampleTurnDeg')}")
    if float(max_errors.get("humpR3ArcSweepDeg", 0)) > 180:
        errors.append(f"standard sweep humpR3ArcSweepDeg exceeds 180: {max_errors.get('humpR3ArcSweepDeg')}")
    if float(max_errors.get("humpR8ArcSweepDeg", 0)) > 135:
        errors.append(f"standard sweep humpR8ArcSweepDeg exceeds 135: {max_errors.get('humpR8ArcSweepDeg')}")
    if float(max_errors.get("humpCount", 0)) != 2:
        errors.append(f"standard sweep should report two mirrored humps, got {max_errors.get('humpCount')!r}")

    override_failures = (sweep.get("overrides") or {}).get("failures") or []
    override_errors = {item for row in override_failures for item in row.get("errors", [])}
    for expected in ["R.8 Q max exceeded", "R.8 L ledge length shortfall"]:
        if expected not in override_errors:
            errors.append(f"diagnostic override sweep is missing expected error: {expected}")


def check_points_json(errors: list[str]) -> None:
    points = json.loads(POINTS_JSON.read_text(encoding="utf-8"))
    source_hash = current_source_hash()
    if points.get("sourceHtmlSha256") != source_hash:
        errors.append("rim fit points JSON was not generated from the current Tyre Designer HTML")
    if points.get("generatedBy") != "tyres/tools/build_tyre_designer_etrto_rim_artifacts.py":
        errors.append(f"unexpected point generator: {points.get('generatedBy')!r}")
    display = points.get("display") or {}
    rim = display.get("rim") or {}
    reference = display.get("referenceRim") or {}
    if len(rim.get("humps") or []) != 2:
        errors.append("rim fit points should contain the two displayed H humps")
    if len(reference.get("humps") or []) != 2:
        errors.append("rim fit points should contain the two reference H humps")


def check_bitmap_scan_overlays(errors: list[str]) -> None:
    source_hash = current_source_hash()
    checks = [
        (
            R8_BITMAP_OVERLAY_SVG,
            R8_BITMAP_OVERLAY_PNG,
            "R.8 bitmap overlay",
            [
                "ETRTO R.8 Bitmap Overlay - Tyre Designer Rim",
                source_hash,
                "Current Tyre Designer full R.8 basic rim contour without H hump",
                "ETRTO R.8 nominal reference contour",
                "sourceHtmlSha256",
            ],
            1200,
            600,
        ),
        (
            R11_BITMAP_OVERLAY_SVG,
            R11_BITMAP_OVERLAY_PNG,
            "R.11 bitmap overlay",
            [
                "ETRTO R.11 Bitmap Overlay - Tyre Designer H Hump",
                source_hash,
                "Current Tyre Designer H hump radius and bead-seat continuation",
                "ETRTO R.11 nominal H-hump reference",
                "sourceHtmlSha256",
            ],
            800,
            600,
        ),
    ]
    for svg_path, png_path, label, markers, min_width, min_height in checks:
        svg = svg_path.read_text(encoding="utf-8")
        for marker in markers:
            if marker not in svg:
                errors.append(f"missing {label} marker: {marker}")
        if svg.count("<polyline") < 2:
            errors.append(f"{label} should contain displayed and reference polylines")
        if 'data:image/png;base64,' not in svg:
            errors.append(f"{label} should embed the ETRTO bitmap crop")
        check_png_file(errors, png_path, f"{label} PNG", min_width=min_width, min_height=min_height)


def check_bitmap_alignment_metrics(errors: list[str]) -> None:
    metrics = json.loads(BITMAP_ALIGNMENT_JSON.read_text(encoding="utf-8"))
    source_hash = current_source_hash()
    if metrics.get("sourceHtmlSha256") != source_hash:
        errors.append("bitmap alignment metrics were not generated from the current Tyre Designer HTML")
    if metrics.get("generatedBy") != "tyres/tools/build_tyre_designer_etrto_rim_artifacts.py":
        errors.append(f"unexpected bitmap alignment generator: {metrics.get('generatedBy')!r}")

    checks = {
        "r8": "R.8 basic rim contour without H hump",
        "r11": "R.11 H hump radius and bead-seat continuation",
    }
    for key, geometry_marker in checks.items():
        row = metrics.get(key) or {}
        if geometry_marker not in str(row.get("geometry", "")):
            errors.append(f"{key} bitmap alignment is missing geometry marker: {geometry_marker}")
        distances = row.get("distancePx") or {}
        point_count = distances.get("pointCount")
        hit_count = distances.get("hitCount")
        miss_count = distances.get("missCount")
        if not isinstance(point_count, int) or point_count <= 0:
            errors.append(f"{key} bitmap alignment has invalid pointCount: {point_count!r}")
        if not isinstance(hit_count, int) or hit_count <= 0:
            errors.append(f"{key} bitmap alignment has invalid hitCount: {hit_count!r}")
        if not isinstance(miss_count, int) or not isinstance(point_count, int) or miss_count >= point_count:
            errors.append(f"{key} bitmap alignment has invalid missCount: {miss_count!r}")
        for metric in ["meanPx", "p90Px", "maxPx"]:
            value = distances.get(metric)
            if not isinstance(value, (int, float)) or not math.isfinite(float(value)):
                errors.append(f"{key} bitmap alignment has invalid {metric}: {value!r}")


def check_reference_notes(errors: list[str]) -> None:
    source = SOURCE_NOTE.read_text(encoding="utf-8")
    for marker in [
        "input/ETRTO-Standards-Manual2017.pdf",
        "pages **R.8** and **R.9**",
        "page **R.11**",
        "H-hump as true tangent circle arcs",
        "tyre_designer_display_rim_overlay.html",
        "etrto_R8_bitmap_overlay.png",
        "etrto_R11_bitmap_overlay.png",
        "etrto_bitmap_alignment_metrics.json",
        "build_tyre_designer_etrto_rim_artifacts.py",
        "test_tyre_designer_etrto_rim_runtime.py",
        "test_tyre_designer_etrto_rim_artifacts.py",
    ]:
        if marker not in source:
            errors.append(f"missing source-note marker: {marker}")

    readme = README.read_text(encoding="utf-8")
    for marker in [
        "visual aids only",
        "not rendered at strict millimetre scale",
        "hard pass/fail check",
        "tyre_designer_display_rim_overlay.html",
        "etrto_R8_bitmap_overlay.png",
        "etrto_R11_bitmap_overlay.png",
        "etrto_bitmap_alignment_metrics.json",
        "build_tyre_designer_etrto_rim_artifacts.py",
    ]:
        if marker not in readme:
            errors.append(f"missing reference README marker: {marker}")


def run_check() -> dict:
    errors: list[str] = []
    required = [
        OVERLAY_HTML,
        DISPLAY_HTML,
        DISPLAY_PNG,
        SWEEP_JSON,
        POINTS_JSON,
        BITMAP_ALIGNMENT_JSON,
        README,
        SOURCE_NOTE,
        HTML_PATH,
        BUILDER_PATH,
        REF_DIR / "etrto_R8_diagram.png",
        REF_DIR / "etrto_R11_diagram.png",
        R8_BITMAP_OVERLAY_SVG,
        R8_BITMAP_OVERLAY_PNG,
        R11_BITMAP_OVERLAY_SVG,
        R11_BITMAP_OVERLAY_PNG,
    ]
    for path in required:
        if not path.is_file():
            errors.append(f"missing artifact: {relative(path)}")

    if not errors:
        check_overlay_html(errors)
        check_png(errors)
        check_sweep_json(errors)
        check_points_json(errors)
        check_bitmap_scan_overlays(errors)
        check_bitmap_alignment_metrics(errors)
        check_reference_notes(errors)

    return {
        "passed": not errors,
        "display_overlay": relative(DISPLAY_HTML),
        "display_overlay_png": relative(DISPLAY_PNG),
        "sweep": relative(SWEEP_JSON),
        "errors": errors,
    }


def main() -> int:
    result = run_check()
    print(json.dumps(result, indent=2))
    return 0 if result["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
