#!/usr/bin/env python3
"""Static smoke checks for the lightweight MATLAB tyre_designer UI."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
APP_DIR = REPO_ROOT / "tyres" / "matlab" / "apps" / "tyre_designer"
HTML_PATH = APP_DIR / "assets" / "tyre_designer.html"
IMPL_PATH = APP_DIR / "tyre_designer_app.m"
PLOT_DATA_PATH = APP_DIR / "tyre_designer_plot_data.m"
ENTRY_PATH = APP_DIR / "tyre_designer.m"
WRAPPER_PATH = APP_DIR / "tyre_designer_open.m"
LEGACY_ENTRY_PATH = REPO_ROOT / "tyres" / "matlab" / "functions" / "tyre_designer.m"
LEGACY_WRAPPER_PATH = REPO_ROOT / "tyres" / "matlab" / "functions" / "tyre_designer_open.m"
MATERIAL_DB_BUILDER_PATH = REPO_ROOT / "tyres" / "tools" / "build_material_database.py"
MATERIAL_DB_PATH = REPO_ROOT / "tyres" / "database" / "rf2_material_database.sqlite"


def run_check() -> dict:
    html = HTML_PATH.read_text(encoding="utf-8")
    impl = IMPL_PATH.read_text(encoding="utf-8")
    plot_data = PLOT_DATA_PATH.read_text(encoding="utf-8")
    entry = ENTRY_PATH.read_text(encoding="utf-8")
    wrapper = WRAPPER_PATH.read_text(encoding="utf-8")
    material_db_builder = MATERIAL_DB_BUILDER_PATH.read_text(encoding="utf-8")
    function_names = set(re.findall(r"\bfunction\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", html))
    errors: list[str] = []

    for path in [HTML_PATH, IMPL_PATH, PLOT_DATA_PATH, ENTRY_PATH, WRAPPER_PATH, MATERIAL_DB_BUILDER_PATH]:
        if not path.is_file():
            errors.append(f"missing file: {path.relative_to(REPO_ROOT)}")
    if not MATERIAL_DB_PATH.is_file():
        errors.append(f"missing file: {MATERIAL_DB_PATH.relative_to(REPO_ROOT)}")
    for path in [LEGACY_ENTRY_PATH, LEGACY_WRAPPER_PATH]:
        if path.exists():
            errors.append(f"tyre designer entrypoint should live in app folder, not: {path.relative_to(REPO_ROOT)}")

    for marker in [
        "function setup(htmlComponent)",
        'id="tyre-select"',
        'command: "loadTgm"',
        "startView",
        "normalizeViewName",
        'data-view="model"',
        'data-view="node-explorer"',
        'data-view="reengineering"',
        'data-view="materials"',
        'id="model-view"',
        'id="node-explorer-view"',
        'id="reengineering-view"',
        'id="materials-view"',
        'id="materials-workspace"',
        "materials-page",
        "materials-workspace",
        "materials-browser",
        "material-filter",
        "material-category-list",
        "material-list",
        "material-row",
        "data-material-category",
        "data-material-id",
        "data-material-action",
        "select-filtered",
        "materials-plot-grid",
        "materials-selection-summary",
        'id="materials-young-chart"',
        'id="materials-density-chart"',
        'id="materials-heat-chart"',
        'id="materials-conductivity-chart"',
        'id="materials-ratio-chart"',
        'id="materials-shore-chart"',
        'id="node-explorer-plot"',
        'id="reengineering-plot"',
        'id="reengineering-matrix"',
        'id="reengineering-candidates"',
        'id="reengineering-family-summary"',
        "Material Reengineering",
        "Node x Material matrix",
        "Family Summary",
        "plyFamilyDefaults",
        "reengineeringFamilyDefaults",
        "reengineeringStackKey",
        "reengineeringFamilyKey",
        "data-reengineering-cell",
        "data-ply-family-key",
        "data-ply-family-candidate-key",
        "data-reengineering-jump",
        "node-explorer-grid",
        "node-overview-panel",
        "node-detail-panel",
        'id="node-detail-plot"',
        'id="node-layer-spread-slider"',
        "data-node-display-target",
        "Node section display",
        "material-teardown-panel",
        'id="node-material-title"',
        'id="node-material-summary"',
        'id="node-material-recognition"',
        "material-recognition",
        "material-match-chip",
        "material-candidate-panel",
        "material-candidate-row",
        "data-material-match-kind",
        "data-material-candidate-key",
        'id="material-young-chart"',
        'id="material-density-chart"',
        'id="material-heat-chart"',
        'id="material-conductivity-chart"',
        'id="material-dimensionless-chart"',
        "grid-auto-rows",
        "Material teardown",
        "material-series-toggle",
        "data-material-series-key",
        "data-material-kind-filter",
        "materialHiddenSeries",
        "materialRecognitionCache",
        "selectedMaterialCandidateKey",
        "materialCandidateDefaults",
        "MATERIAL_GLOBAL_DOMINANCE_SCOPES",
        "MATERIAL_GLOBAL_DISTANCE_MARGIN",
        "dominantByScope",
        "sourceFamily",
        "globalOverride",
        "materialMatchScopeKey",
        "sharedScopeCount",
        "responsivePlotObserver",
        "ResizeObserver",
        "syncSvgViewBox",
        "MATERIAL_RECOGNITION_TOP_N",
        "materialIndex",
        "materialRecognitionData",
        "materialMultiplierRangeText",
        "modulusMultiplier",
        "densityMultiplier",
        "globalProbability",
        "Young's modulus",
        "Temperature [C]",
        "no pressure-dependent material rows",
        "Node spread",
        "Model View",
        "Node Explorer",
        "Materials",
        "drawGeometry",
        "drawGeometryPlot",
        "drawNodeExplorer",
        "drawReengineering",
        "drawNodeDetail",
        "drawMaterialsPage",
        "materialLibraryData",
        "selectedLibraryMaterials",
        "materialLibraryPropertySeries",
        "materialLibraryConductivitySeries",
        "materialLibraryDimensionlessSeries",
        "drawRubber",
        "drawLayers",
        'id="layer-explode-enabled"',
        'id="layer-explode-slider"',
        "viewState",
        "plotHitMaps",
        "nodeSelectionDrag",
        "node-selection-box",
        "focusKey",
        "selectedNodeIndex",
        "selectedNodeIndices",
        'tabindex="0"',
        "keydown",
        "ArrowRight",
        "PageDown",
        "data-node-index",
        "data-focus-key",
        "layerExplode",
        "layerExplodeEnabled",
        "nodeLayerSpread",
        "nodeShowLayers",
        "nodeShowRest",
        "LAYER_EXPLODE_TARGET_MM",
        "NODE_LAYER_SPREAD_TARGET_MM",
        "NODE_REST_SPREAD_TARGET_MM",
        "NODE_SLICE_LABEL_MIN_GAP_PX",
        "TD",
        "NT",
        "Layer spread",
        "applyLayerExplosion",
        "explodedLayerGap",
        "materials",
        "nodeCloneGroups",
        "nodeCloneProfile",
        "nodeMarkerStyle",
        "drawCloneLegend",
        "rubberCrossSection",
        "plyCrossSection",
        "nodeThicknessM",
        "treadXMm",
        "Node thickness",
        "drawLineCallouts",
        "calloutSpecs",
        "layerNodeStats",
        "chooseCalloutTargets",
        "medianCandidateY",
        "arrangeCalloutOrder",
        "relaxCalloutSpacing",
        "orderedCalloutCandidates",
        "layerDepthOrderedCandidates",
        "scoreCalloutCandidate",
        "screenDistance",
        "nearestLabelObstacleY",
        "treadInnerReferenceY",
        "drawNodeLayerGuides",
        "deepestLayerByNode",
        "node-layer-guide",
        "drawNodeNumbers",
        "node-label",
        "layoutCallouts",
        "nearestLayerRow",
    ]:
        if marker not in html:
            errors.append(f"missing HTML marker: {marker}")

    for function_name in [
        "drawGeometry",
        "drawGeometryPlot",
        "drawNodeExplorer",
        "drawNodeDetail",
        "drawMaterialsPage",
        "bindResponsivePlotSizing",
        "observeResponsiveSvgs",
        "queueResponsivePlotRender",
        "syncSvgViewBox",
        "handleMaterialsWorkspaceInput",
        "handleMaterialsWorkspaceChange",
        "handleMaterialsWorkspaceClick",
        "materialLibraryData",
        "materialLibraryMaterials",
        "materialLibraryCategories",
        "ensureMaterialBrowserState",
        "filteredMaterialLibraryMaterials",
        "selectedLibraryMaterials",
        "setMaterialCategory",
        "toggleMaterialSelection",
        "rememberMaterialScrollPositions",
        "restoreMaterialScrollPositions",
        "captureMaterialFocusState",
        "restoreMaterialFocusState",
        "materialListRowHtml",
        "drawMaterialsLibraryPlots",
        "materialLibraryPropertySeries",
        "materialLibraryConductivitySeries",
        "materialLibraryDimensionlessSeries",
        "materialLibraryPoints",
        "materialTemperatureRangeText",
        "materialModulusRangeText",
        "materialShortLabel",
        "materialLibraryColor",
        "asArray",
        "selectedNodeIndexOrDefault",
        "selectedNodeIndicesOrDefault",
        "selectedNodeSet",
        "selectedNodeLabel",
        "buildNodeSectionGroups",
        "nodeSectionLayoutMetrics",
        "nodeSectionXScale",
        "nodeSectionXAt",
        "nodeSectionGroupKey",
        "drawNodeSectionGroupLegend",
        "drawNodeSectionHeaderLabels",
        "nodeLayerPreviewInfo",
        "nodeLayerMaterialToken",
        "drawNodeSliceBand",
        "drawNodeSliceLabels",
        "chooseNodeSliceLabels",
        "selectAlternatingNodeSliceLabels",
        "textGapPx",
        "estimateNodeSliceLabelWidth",
        "drawNodeSliceLegend",
        "drawNodeSliceLegendRow",
        "drawMaterialTeardown",
        "plyReengineeringModel",
        "ensureReengineeringSelection",
        "drawReengineeringMatrix",
        "drawReengineeringDecision",
        "drawReengineeringFamilySummary",
        "plyCellKey",
        "reengineeringCellKey",
        "materialStackKey",
        "materialStackLabel",
        "materialStackSortValue",
        "plyMaterialSignatureKey",
        "materialFamilySignatureKey",
        "plyFamilyDefaultBaseKey",
        "reengineeringFamilyDefaultBaseKey",
        "selectPlyFamilyCandidateDefault",
        "selectReengineeringCell",
        "selectReengineeringFamily",
        "jumpToReengineeringFamily",
        "plyFamilyFlags",
        "plyFamilyCandidateWithMaterial",
        "reengineeringFamilyCandidateWithMaterial",
        "plyCandidateShortLabel",
        "reengineeringMaterialLabel",
        "plyFamilyLabel",
        "reengineeringCellTitle",
        "reengineeringCellMeta",
        "plyFamilyObservedPropertySeries",
        "plyFamilyObservedDimensionlessSeries",
        "nodeRangeText",
        "rangeText",
        "familyCoverageBars",
        "consecutiveRanges",
        "nodeMaterialPreviewInfo",
        "drawReengineeringLayerHighlights",
        "toggleMaterialKindFilter",
        "filterMaterialRowsByKind",
        "toggleMaterialSeries",
        "materialSeriesVisibilityKey",
        "isMaterialSeriesHidden",
        "toggleMaterialCandidatePanel",
        "selectMaterialCandidateDefault",
        "toggleSelectedMaterialCandidate",
        "materialCandidateKey",
        "parseMaterialCandidateKey",
        "materialCandidateDefaultForKind",
        "selectedMaterialCandidateForNodes",
        "materialLibraryMaterialForCandidate",
        "materialCandidateMultiplier",
        "materialRowsForNode",
        "materialRowsForNodes",
        "sortMaterialRows",
        "materialKindOrder",
        "materialKindLabel",
        "materialKindShort",
        "materialKindColor",
        "materialKindDash",
        "nodeSeriesColor",
        "temperatureC",
        "materialPressureFields",
        "drawMaterialSummary",
        "drawMaterialRecognition",
        "aggregateSelectedMaterialMatches",
        "aggregateSelectedMaterialCandidateAlternatives",
        "materialCandidateScopeText",
        "drawMaterialCandidatePanel",
        "dominantMatchType",
        "materialMultiplierRangeText",
        "materialRecognitionData",
        "observedMaterialGroups",
        "materialGroupPlyIndex",
        "materialMatchScopeKey",
        "materialMatchScopeLabel",
        "fallbackMaterialIndex",
        "dedupeMaterialCandidates",
        "isMaterialCandidateForKind",
        "matchMaterialCandidate",
        "normalizedMaterialPoint",
        "interpolateMaterialValue",
        "scaledLogFit",
        "logResidual",
        "absoluteResidual",
        "scalePlausibilityPenalty",
        "aggregateGlobalMaterialMatches",
        "enrichMaterialMatches",
        "materialGlobalDominanceOverride",
        "materialSourceFamilyKey",
        "materialCandidateLikelihood",
        "materialMatchType",
        "materialIdentityKey",
        "materialCandidatePropertySeries",
        "materialCandidateDimensionlessSeries",
        "materialPropertySeries",
        "mergeMaterialSeriesPoints",
        "materialDimensionlessSeries",
        "drawMaterialTrendChart",
        "drawMaterialSeriesLegend",
        "drawMaterialEmptyChart",
        "materialPlotDomain",
        "materialNiceStep",
        "materialNiceFloor",
        "materialNiceCeil",
        "updateNodeLayerSpreadReadout",
        "updateNodeDisplayControls",
        "toggleNodeDisplayTarget",
        "normalizeNodeDisplayTarget",
        "nodeSectionVisibility",
        "nodeLayerSpreadStrength",
        "handleNodeClickSelection",
        "handleNodeExplorerKeydown",
        "nodeExplorerNodeIndices",
        "beginNodeSelectionDrag",
        "updateNodeSelectionDrag",
        "finishNodeSelectionDrag",
        "cancelNodeSelectionDrag",
        "drawNodeSelectionBox",
        "clearNodeSelectionBox",
        "selectionRectFromPoints",
        "nodesInSelectionRect",
        "applyNodeBoxSelection",
        "selectNode",
        "toggleSelectedNode",
        "setSelectedNodes",
        "sameNode",
        "storeNodeHitMap",
        "nearestNodeFromEvent",
        "nearestNodeHit",
        "svgPointFromEvent",
        "nodeCloneGroups",
        "nodeCloneProfile",
        "nodeMarkerStyle",
        "drawCloneLegend",
        "numberKey",
        "drawRubber",
        "drawLayers",
        "setCurrentView",
        "normalizeViewName",
        "renderCurrentView",
        "toggleGeometryFocus",
        "geometryFocusKey",
        "focusOpacity",
        "focusStrokeOpacity",
        "updateLayerExplodeReadout",
        "layerExplodeStrength",
        "applyLayerExplosion",
        "buildNodeLayerSpreadPlan",
        "buildNodeRestSpreadPlan",
        "shiftNodeLayerPlan",
        "nodeRestReferenceGapMm",
        "explodedRestGap",
        "layerReferenceGapMm",
        "explodedLayerGap",
        "layerExplosionUnit",
        "layerInnerOffsetMm",
        "layerOuterOffsetMm",
        "layerThicknessMm",
        "positiveLayerGapMm",
        "fmtMm",
        "drawLineCallouts",
        "calloutSpecs",
        "layerNodeStats",
        "chooseCalloutTargets",
        "medianCandidateY",
        "arrangeCalloutOrder",
        "relaxCalloutSpacing",
        "orderedCalloutCandidates",
        "layerDepthOrderedCandidates",
        "scoreCalloutCandidate",
        "nearestLabelObstacleY",
        "treadInnerReferenceY",
        "drawNodeLayerGuides",
        "deepestLayerByNode",
        "drawNodeNumbers",
        "layoutCallouts",
        "makeFrame",
        "drawAxes",
    ]:
        if function_name not in function_names:
            errors.append(f"missing JS function: {function_name}")

    for marker in [
        "sqlite(dbPath, \"readonly\")",
        "uigridlayout(fig, [1 1]",
        "fig.WindowState = \"maximized\"",
        "from tyres order by display_name",
        "rf2_material_database.sqlite",
        "state.materialDatabase",
        "state.materialLibrary",
        "localMaterialDatabaseInfo",
        "localLoadMaterialLibraryDatabase",
        "from material_points order by material_id",
        "localMaterialRecords",
        "localMaterialPointRecords",
        "tyre_designer_read_tgm(inputPath)",
        "tyre_designer_plot_data(model)",
        "tyre_designer_project_root()",
        "options.StartView",
        '"materials"',
        '"reengineering"',
        "localNormalizeStartView",
        "state.startView",
        "encoded.rubberCrossSection",
        "encoded.materials",
    ]:
        if marker not in impl:
            errors.append(f"missing MATLAB marker: {marker}")

    for marker in [
        "materialPlyIndex",
        "'plyIndex'",
    ]:
        if marker not in plot_data:
            errors.append(f"missing plot-data marker: {marker}")

    for forbidden in [
        "localLoadInputModel",
        "rf2TgmGenExtractInputsImpl",
        "localLoadMaterialLibrary(",
        "rf2TgmGenMaterialLibraryImpl",
        "localLoadChartReport",
    ]:
        if forbidden in impl:
            errors.append(f"tyre_designer still depends on slow ODS path: {forbidden}")

    if "function varargout = tyre_designer(varargin)" not in entry:
        errors.append("missing clean tyre_designer entrypoint")
    if "tyre_designer_app(varargin{:})" not in entry:
        errors.append("entrypoint does not call tyre_designer_app")
    for marker in [
        "function varargout = tyre_designer_open(tyre, options)",
        "options.Menu",
        "options.View",
        '"StartView", startView',
        '"reengineering"',
        "tyre_designer(tyre",
        "localCloseExistingTyreDesignerInstances",
        'findall(groot, "Type", "figure", "Name", "tyre_designer")',
        "delete(figures(isvalid(figures)))",
    ]:
        if marker not in wrapper:
            errors.append(f"missing wrapper marker: {marker}")
    for marker in [
        "extract_material_library",
        "rf2_material_database.sqlite",
        "create table categories",
        "create table materials",
        "create table material_points",
        "youngs_modulus_pa",
        "longitudinal_conductivity",
        "shore_a",
    ]:
        if marker not in material_db_builder:
            errors.append(f"missing material DB builder marker: {marker}")
    forbidden_names = [
        "rf2TgmGeometry",
        "rf2TyreDesigner",
        "tgm_geometry",
        "tgm_generator",
        "rf2TgmAppPath",
    ]
    for forbidden_name in forbidden_names:
        if forbidden_name in impl or forbidden_name in entry:
            errors.append(f"legacy app reference remains: {forbidden_name}")

    return {
        "passed": not errors,
        "html": str(HTML_PATH.relative_to(REPO_ROOT)),
        "matlab_impl": str(IMPL_PATH.relative_to(REPO_ROOT)),
        "entrypoint": str(ENTRY_PATH.relative_to(REPO_ROOT)),
        "errors": errors,
    }


def main() -> int:
    report = run_check()
    print(json.dumps(report, indent=2))
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
